CPPFLAGS=-I/opt/ros/diamondback/stacks/vision_opencv/opencv2/opencv/include 
LDFLAGS=-L/opt/ros/diamondback/stacks/vision_opencv/opencv2/opencv/lib -lopencv_core -lopencv_highgui

all:
	g++ -g proto_pipe_finder.cpp ${CPPFLAGS} ${LDFLAGS} -o cvtest

