"""autogenerated by genmsg_py from Vector3Masked.msg. Do not edit."""
import roslib.message
import struct

import geometry_msgs.msg

class Vector3Masked(roslib.message.Message):
  _md5sum = "b14f0eeff8b4ac7d2f898ca7d64021af"
  _type = "seabee3_msgs/Vector3Masked"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """geometry_msgs/Vector3 mask
geometry_msgs/Vector3 mode
geometry_msgs/Vector3 values

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 

float64 x
float64 y
float64 z
"""
  __slots__ = ['mask','mode','values']
  _slot_types = ['geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       mask,mode,values
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(Vector3Masked, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.mask is None:
        self.mask = geometry_msgs.msg.Vector3()
      if self.mode is None:
        self.mode = geometry_msgs.msg.Vector3()
      if self.values is None:
        self.values = geometry_msgs.msg.Vector3()
    else:
      self.mask = geometry_msgs.msg.Vector3()
      self.mode = geometry_msgs.msg.Vector3()
      self.values = geometry_msgs.msg.Vector3()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_9d.pack(_x.mask.x, _x.mask.y, _x.mask.z, _x.mode.x, _x.mode.y, _x.mode.z, _x.values.x, _x.values.y, _x.values.z))
    except struct.error, se: self._check_types(se)
    except TypeError, te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      if self.mask is None:
        self.mask = geometry_msgs.msg.Vector3()
      if self.mode is None:
        self.mode = geometry_msgs.msg.Vector3()
      if self.values is None:
        self.values = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 72
      (_x.mask.x, _x.mask.y, _x.mask.z, _x.mode.x, _x.mode.y, _x.mode.z, _x.values.x, _x.values.y, _x.values.z,) = _struct_9d.unpack(str[start:end])
      return self
    except struct.error, e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_9d.pack(_x.mask.x, _x.mask.y, _x.mask.z, _x.mode.x, _x.mode.y, _x.mode.z, _x.values.x, _x.values.y, _x.values.z))
    except struct.error, se: self._check_types(se)
    except TypeError, te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      if self.mask is None:
        self.mask = geometry_msgs.msg.Vector3()
      if self.mode is None:
        self.mode = geometry_msgs.msg.Vector3()
      if self.values is None:
        self.values = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 72
      (_x.mask.x, _x.mask.y, _x.mask.z, _x.mode.x, _x.mode.y, _x.mode.z, _x.values.x, _x.values.y, _x.values.z,) = _struct_9d.unpack(str[start:end])
      return self
    except struct.error, e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_9d = struct.Struct("<9d")
