#!/bin/bash

###########################################################################
#  scripts/add_license.sh
#  --------------------
#
#  Software License Agreement (BSD License)
#
#  Copyright (c) 2013, Edward T. Kaszubski ( ekaszubski@gmail.com ), Dylan Foster
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are
#  met:
#
#  * Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#  * Redistributions in binary form must reproduce the above
#    copyright notice, this list of conditions and the following disclaimer
#    in the documentation and/or other materials provided with the
#    distribution.
#  * Neither the name of usc-ros-pkg nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
#  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
#  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
#  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
#  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
#  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
#  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
#  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
#  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
#  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
##########################################################################

usage()
{
    echo ""
    echo "Usage: uscauv-add-license [-p project] [-u user] [-f] files"
    echo ""
}

if [ $# -le 0 ]; then
    usage
    exit
fi

force="0"

while [ "$1" != "" ]; do
    case $1 in
	-p )        shift
	    project=$1
	    shift
	    ;;
	-f ) shift;
	    force="1"
	    ;;
	-u )        shift
	    if [ "$users" == "" ]; then
		users="$1"
	    else
		users="$users, $1"
	    fi
	    shift
	    ;;
	--help )    usage
	    exit
	    ;;
	* )         if [ "$1" != "" ] && [ "$1" != "-p" ] && [ "$1" != "--help" ] && [ "$1" != "-u" ]; then
	    targets="$targets $1"
	    shift
	    fi
	    ;;
    esac
done

if [ "$project" == "" ]; then project="USC AUV"; fi

if [ "$users" == "" ]; then 
    if [ -n "$USCAUV_USER" ]; then
	users="$USCAUV_USER"
    else
    	users=`whoami` 
    fi
fi

echo ""
echo "Adding license with authors { $users } and project \"$project\" to files { $targets }"
echo ""

year=`date | awk '{print $6;}'`

license_c_part1="/***************************************************************************
 *  "
    license_c_part2="
 *  --------------------
 *
 *  Software License Agreement (BSD License)
 *
 *  Copyright (c) $year, $users
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions are
 *  met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following disclaimer
 *    in the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of $project nor the names of its
 *    contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  \"AS IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 **************************************************************************/

"
    license_script_part1="###########################################################################
#  "
    license_script_part2="
#  --------------------
#
#  Copyright (c) $year, $users
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are
#  met:
#
#  # Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#  # Redistributions in binary form must reproduce the above
#    copyright notice, this list of conditions and the following disclaimer
#    in the documentation and/or other materials provided with the
#    distribution.
#  # Neither the name of $project nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
#  \"AS IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
#  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
#  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
#  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
#  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
#  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
#  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
#  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
#  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
##########################################################################

"

script_ext="py yaml yml bash sh cmake txt rviz"
c_ext="c cpp h hpp cc cxx hxx"

for target in $targets; do

    ext="${target#*.}"

    shopt -s nocasematch

    if grep -qw "$ext" <<<$script_ext; then
	license_part1=$license_script_part1
	license_part2=$license_script_part2
    elif grep -qw "$ext" <<<$c_ext; then
	license_part1=$license_c_part1
	license_part2=$license_c_part2
    else
	license_part1=$license_script_part1
	license_part2=$license_script_part2
    fi

    file_contents=`cat $target`

    # Dump the original file contents in case there is an error
    if [ "$force" -ne "1" -a -n "$file_contents" ]; then
	echo "$file_contents" > $target~
    fi

    echo "$license_part1$target$license_part2$file_contents" > $target

done

shopt -u nocasematch

echo "done"
