#!/bin/bash

###########################################################################
#  uscauv-add-node
#  --------------------
#
#  Copyright (c) 2013, Dylan Foster
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are
#  met:
#
#  # Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#  # Redistributions in binary form must reproduce the above
#    copyright notice, this list of conditions and the following disclaimer
#    in the documentation and/or other materials provided with the
#    distribution.
#  # Neither the name of USC AUV nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
#  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
#  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
#  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
#  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
#  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
#  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
#  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
#  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
#  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
###########################################################################


# Parse commands ###############################################

function usage()
{
    echo "usage: `basename $0` package node [-u user] [-p project]"
}

if [ $# -lt 2 ]; then
    usage
    exit
fi

package_name=$1; shift
node_name=$1; shift

package_path=`rospack find $package_name`
if [ -z "$package_path" ]; then exit; fi

while (( "$#" )); do

    case $1 in
	-p ) shift
	    if [ -n "$project" ]; then
		usage
		exit
	    else
		project=$1
		shift
	    fi
	    ;;
	-u ) shift
	    if [ -z "$users" ]; then
		users="$1"
	    else
		users="$users, $1"
	    fi
	    shift
	    ;;
	* ) 
	    if [ -n "$1" ]; then
		usage
		exit
	    else
		shift
	    fi
	    ;;
    esac
done

if [ -z "$project" ]; then project="USC AUV"; fi
if [ -z "$users" ]; then users=`whoami`; fi

# Process Text #################################################


NodeName=`echo $node_name | sed 's/[a-z]/\U&/' |sed 's/_[a-z]/\U\0/g' | tr -d _`
NODENAME=`echo $node_name | sed 's/[a-z]/\U&/g'| tr -d _`

PackageName=`echo $package_name | sed 's/[a-z]/\U&/' |sed 's/_[a-z]/\U\0/g' | tr -d _`
PACKAGENAME=`echo $package_name | sed 's/[a-z]/\U&/g' | tr -d _`

header_file="$node_name.h"
cpp_file="$node_name.cpp"

include_path="include/$package_name"
src_path="src"

header_path="$include_path/$header_file"
cpp_path="$src_path/$cpp_file"

IFNDEF_TEXT="USCAUV_"$PACKAGENAME"_"$NODENAME""

header_text="
#ifndef $IFNDEF_TEXT
#define $IFNDEF_TEXT

// ROS
#include <ros/ros.h>

// uscauv
#include <uscauv_common/base_node.h>

class "$NodeName"Node: public BaseNode
{
  
 public:
  "$NodeName"Node(): BaseNode(\"$NodeName\")
   {
   }

 private:

  // Running spin() will cause this function to be called before the node begins looping the spinOnce() function.
  void spinFirst()
     {
	 
     }  

  // Running spin() will cause this function to get called at the loop rate until this node is killed.
  void spinOnce()
     {

     }

};

#endif // $IFNDEF_TEXT"

cpp_text="
#include <$package_name/$header_file>

// Initialize "$NodeName"Node and begin looping.
int main(int argc, char ** argv)
{
  ros::init(argc, argv, \"$node_name\");

  "$NodeName"Node $node_name;

  $node_name.spin();

  return 0;
}"

# Make the magic happen ########################################

cd $package_path

if [ ! -d  "$include_path" ]; then
    mkdir -vp $include_path
fi
if [ ! -d  "$src_path" ]; then
    mkdir -vp $src_path
fi

echo "$header_text" > $header_path
echo "$cpp_text" > $cpp_path

uscauv-add-license -u "$users" -p "$project" $header_path $cpp_path